AUTH_PROVIDER_EMAIL = "email"
AUTH_PROVIDER_GOOGLE = "google"
AUTH_PROVIDERS = [AUTH_PROVIDER_EMAIL, AUTH_PROVIDER_GOOGLE]

OTP_LENGTH = 6
OTP_EXPIRY_MINUTES = 10

PASSWORD_RESET_EXPIRY_MINUTES = 15
PASSWORD_RESET_TOKEN_PURPOSE = "password_reset"  # nosec B105 - a JWT claim value, not a credential
